obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[ 0.6,  0.6], [-0.6,  0.6], [-0.6, -0.6], [ 0.6, -0.6]]
footprint_padding: 0.03
#robot_radius: ir_of_robot
inflation_radius: 0.55
transform_tolerance: 1

controller_patience: 2.0

NavfnROS:
    allow_unknown: true

recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear: 
    reset_distance: 3.00
aggressive_clear:
    reset_distance: 1.84


observation_sources: point_cloud_sensor

# assuming receiving a cloud from rtabmap_ros/obstacles_detection node
point_cloud_sensor: {
    # TODO set sensor frame to location of stereo camera
    sensor_frame: base_link,
    data_type: PointCloud2,
    topic: planner_cloud,
    expected_update_rate: 20.0,
    marking: true,
    clearing: true,
    min_obstacle_height: -99999.0,
    max_obstacle_height: 99999.0}
