# Configuration for global_costmap
# see http://wiki.ros.org/navigation/Tutorials/RobotSetup

global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
