local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 2.0
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.025
    origin_x: -2.0
    origin_y: -2.0

    observation_sources: point_cloud_sensor

    # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
    point_cloud_sensor: {
        # TODO set sensor fram to location of stereo camera
        sensor_frame: base_link,
        data_type: PointCloud2, 
        topic: /rtabmap/cloud_map,
        expected_update_rate: 0.5, 
        marking: true, 
        clearing: true,
        min_obstacle_height: -99999.0,
        max_obstacle_height: 99999.0}
